language: node_js
node_js:
  - '8'
branches:
  only:
    - master
os: osx
before_install:
  - npm install -g react-native-cli
  - npm install -g detox-cli
addons:
  homebrew:
    taps: wix/brew
    packages: wix/brew/applesimutils
