language: node_js
node_js:
  - '8'
os:
  - linux
  - osx

matrix:
  fast_finish: true

addons:
  homebrew:
    taps: wix/brew
    packages: wix/brew/applesimutils

script: yarn ci
branches:
  only:
    - master

deploy:
  provider: pages
  local-dir: devkit/out
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
    condition: $TRAVIS_OS_NAME = linux
